// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.plethora.TestworkClevertec2021.dto;

public interface ListOfNewsTitleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOfNewsTitle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .NewsDtoTitle newsDtoTitles = 1;</code>
   */
  java.util.List<com.plethora.TestworkClevertec2021.dto.NewsDtoTitle> 
      getNewsDtoTitlesList();
  /**
   * <code>repeated .NewsDtoTitle newsDtoTitles = 1;</code>
   */
  com.plethora.TestworkClevertec2021.dto.NewsDtoTitle getNewsDtoTitles(int index);
  /**
   * <code>repeated .NewsDtoTitle newsDtoTitles = 1;</code>
   */
  int getNewsDtoTitlesCount();
  /**
   * <code>repeated .NewsDtoTitle newsDtoTitles = 1;</code>
   */
  java.util.List<? extends com.plethora.TestworkClevertec2021.dto.NewsDtoTitleOrBuilder> 
      getNewsDtoTitlesOrBuilderList();
  /**
   * <code>repeated .NewsDtoTitle newsDtoTitles = 1;</code>
   */
  com.plethora.TestworkClevertec2021.dto.NewsDtoTitleOrBuilder getNewsDtoTitlesOrBuilder(
      int index);
}
