// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.plethora.TestworkClevertec2021.dto;

public interface ListOfCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOfComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  java.util.List<com.plethora.TestworkClevertec2021.dto.CommentDto> 
      getCommentsList();
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  com.plethora.TestworkClevertec2021.dto.CommentDto getComments(int index);
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  java.util.List<? extends com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder> 
      getCommentsOrBuilderList();
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder getCommentsOrBuilder(
      int index);
}
