// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.plethora.TestworkClevertec2021.dto;

/**
 * Protobuf type {@code ListOfComment}
 */
public final class ListOfComment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListOfComment)
    ListOfCommentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListOfComment.newBuilder() to construct.
  private ListOfComment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListOfComment() {
    comments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListOfComment();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListOfComment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              comments_ = new java.util.ArrayList<com.plethora.TestworkClevertec2021.dto.CommentDto>();
              mutable_bitField0_ |= 0x00000001;
            }
            comments_.add(
                input.readMessage(com.plethora.TestworkClevertec2021.dto.CommentDto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        comments_ = java.util.Collections.unmodifiableList(comments_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.plethora.TestworkClevertec2021.dto.Dto.internal_static_ListOfComment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.plethora.TestworkClevertec2021.dto.Dto.internal_static_ListOfComment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.plethora.TestworkClevertec2021.dto.ListOfComment.class, com.plethora.TestworkClevertec2021.dto.ListOfComment.Builder.class);
  }

  public static final int COMMENTS_FIELD_NUMBER = 1;
  private java.util.List<com.plethora.TestworkClevertec2021.dto.CommentDto> comments_;
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.plethora.TestworkClevertec2021.dto.CommentDto> getCommentsList() {
    return comments_;
  }
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder> 
      getCommentsOrBuilderList() {
    return comments_;
  }
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  @java.lang.Override
  public int getCommentsCount() {
    return comments_.size();
  }
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  @java.lang.Override
  public com.plethora.TestworkClevertec2021.dto.CommentDto getComments(int index) {
    return comments_.get(index);
  }
  /**
   * <code>repeated .CommentDto comments = 1;</code>
   */
  @java.lang.Override
  public com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder getCommentsOrBuilder(
      int index) {
    return comments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < comments_.size(); i++) {
      output.writeMessage(1, comments_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < comments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, comments_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.plethora.TestworkClevertec2021.dto.ListOfComment)) {
      return super.equals(obj);
    }
    com.plethora.TestworkClevertec2021.dto.ListOfComment other = (com.plethora.TestworkClevertec2021.dto.ListOfComment) obj;

    if (!getCommentsList()
        .equals(other.getCommentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCommentsCount() > 0) {
      hash = (37 * hash) + COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getCommentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.plethora.TestworkClevertec2021.dto.ListOfComment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.plethora.TestworkClevertec2021.dto.ListOfComment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListOfComment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListOfComment)
      com.plethora.TestworkClevertec2021.dto.ListOfCommentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.plethora.TestworkClevertec2021.dto.Dto.internal_static_ListOfComment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.plethora.TestworkClevertec2021.dto.Dto.internal_static_ListOfComment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.plethora.TestworkClevertec2021.dto.ListOfComment.class, com.plethora.TestworkClevertec2021.dto.ListOfComment.Builder.class);
    }

    // Construct using com.plethora.TestworkClevertec2021.dto.ListOfComment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (commentsBuilder_ == null) {
        comments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        commentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.plethora.TestworkClevertec2021.dto.Dto.internal_static_ListOfComment_descriptor;
    }

    @java.lang.Override
    public com.plethora.TestworkClevertec2021.dto.ListOfComment getDefaultInstanceForType() {
      return com.plethora.TestworkClevertec2021.dto.ListOfComment.getDefaultInstance();
    }

    @java.lang.Override
    public com.plethora.TestworkClevertec2021.dto.ListOfComment build() {
      com.plethora.TestworkClevertec2021.dto.ListOfComment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.plethora.TestworkClevertec2021.dto.ListOfComment buildPartial() {
      com.plethora.TestworkClevertec2021.dto.ListOfComment result = new com.plethora.TestworkClevertec2021.dto.ListOfComment(this);
      int from_bitField0_ = bitField0_;
      if (commentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          comments_ = java.util.Collections.unmodifiableList(comments_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.comments_ = comments_;
      } else {
        result.comments_ = commentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.plethora.TestworkClevertec2021.dto.ListOfComment) {
        return mergeFrom((com.plethora.TestworkClevertec2021.dto.ListOfComment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.plethora.TestworkClevertec2021.dto.ListOfComment other) {
      if (other == com.plethora.TestworkClevertec2021.dto.ListOfComment.getDefaultInstance()) return this;
      if (commentsBuilder_ == null) {
        if (!other.comments_.isEmpty()) {
          if (comments_.isEmpty()) {
            comments_ = other.comments_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCommentsIsMutable();
            comments_.addAll(other.comments_);
          }
          onChanged();
        }
      } else {
        if (!other.comments_.isEmpty()) {
          if (commentsBuilder_.isEmpty()) {
            commentsBuilder_.dispose();
            commentsBuilder_ = null;
            comments_ = other.comments_;
            bitField0_ = (bitField0_ & ~0x00000001);
            commentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommentsFieldBuilder() : null;
          } else {
            commentsBuilder_.addAllMessages(other.comments_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.plethora.TestworkClevertec2021.dto.ListOfComment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.plethora.TestworkClevertec2021.dto.ListOfComment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.plethora.TestworkClevertec2021.dto.CommentDto> comments_ =
      java.util.Collections.emptyList();
    private void ensureCommentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        comments_ = new java.util.ArrayList<com.plethora.TestworkClevertec2021.dto.CommentDto>(comments_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plethora.TestworkClevertec2021.dto.CommentDto, com.plethora.TestworkClevertec2021.dto.CommentDto.Builder, com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder> commentsBuilder_;

    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public java.util.List<com.plethora.TestworkClevertec2021.dto.CommentDto> getCommentsList() {
      if (commentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(comments_);
      } else {
        return commentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public int getCommentsCount() {
      if (commentsBuilder_ == null) {
        return comments_.size();
      } else {
        return commentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public com.plethora.TestworkClevertec2021.dto.CommentDto getComments(int index) {
      if (commentsBuilder_ == null) {
        return comments_.get(index);
      } else {
        return commentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder setComments(
        int index, com.plethora.TestworkClevertec2021.dto.CommentDto value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.set(index, value);
        onChanged();
      } else {
        commentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder setComments(
        int index, com.plethora.TestworkClevertec2021.dto.CommentDto.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.set(index, builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder addComments(com.plethora.TestworkClevertec2021.dto.CommentDto value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.add(value);
        onChanged();
      } else {
        commentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder addComments(
        int index, com.plethora.TestworkClevertec2021.dto.CommentDto value) {
      if (commentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommentsIsMutable();
        comments_.add(index, value);
        onChanged();
      } else {
        commentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder addComments(
        com.plethora.TestworkClevertec2021.dto.CommentDto.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.add(builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder addComments(
        int index, com.plethora.TestworkClevertec2021.dto.CommentDto.Builder builderForValue) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.add(index, builderForValue.build());
        onChanged();
      } else {
        commentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder addAllComments(
        java.lang.Iterable<? extends com.plethora.TestworkClevertec2021.dto.CommentDto> values) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, comments_);
        onChanged();
      } else {
        commentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder clearComments() {
      if (commentsBuilder_ == null) {
        comments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        commentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public Builder removeComments(int index) {
      if (commentsBuilder_ == null) {
        ensureCommentsIsMutable();
        comments_.remove(index);
        onChanged();
      } else {
        commentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public com.plethora.TestworkClevertec2021.dto.CommentDto.Builder getCommentsBuilder(
        int index) {
      return getCommentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder getCommentsOrBuilder(
        int index) {
      if (commentsBuilder_ == null) {
        return comments_.get(index);  } else {
        return commentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public java.util.List<? extends com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder> 
         getCommentsOrBuilderList() {
      if (commentsBuilder_ != null) {
        return commentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(comments_);
      }
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public com.plethora.TestworkClevertec2021.dto.CommentDto.Builder addCommentsBuilder() {
      return getCommentsFieldBuilder().addBuilder(
          com.plethora.TestworkClevertec2021.dto.CommentDto.getDefaultInstance());
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public com.plethora.TestworkClevertec2021.dto.CommentDto.Builder addCommentsBuilder(
        int index) {
      return getCommentsFieldBuilder().addBuilder(
          index, com.plethora.TestworkClevertec2021.dto.CommentDto.getDefaultInstance());
    }
    /**
     * <code>repeated .CommentDto comments = 1;</code>
     */
    public java.util.List<com.plethora.TestworkClevertec2021.dto.CommentDto.Builder> 
         getCommentsBuilderList() {
      return getCommentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.plethora.TestworkClevertec2021.dto.CommentDto, com.plethora.TestworkClevertec2021.dto.CommentDto.Builder, com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder> 
        getCommentsFieldBuilder() {
      if (commentsBuilder_ == null) {
        commentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.plethora.TestworkClevertec2021.dto.CommentDto, com.plethora.TestworkClevertec2021.dto.CommentDto.Builder, com.plethora.TestworkClevertec2021.dto.CommentDtoOrBuilder>(
                comments_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        comments_ = null;
      }
      return commentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListOfComment)
  }

  // @@protoc_insertion_point(class_scope:ListOfComment)
  private static final com.plethora.TestworkClevertec2021.dto.ListOfComment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.plethora.TestworkClevertec2021.dto.ListOfComment();
  }

  public static com.plethora.TestworkClevertec2021.dto.ListOfComment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListOfComment>
      PARSER = new com.google.protobuf.AbstractParser<ListOfComment>() {
    @java.lang.Override
    public ListOfComment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListOfComment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListOfComment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListOfComment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.plethora.TestworkClevertec2021.dto.ListOfComment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

