// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package com.plethora.TestworkClevertec2021.dto;

public interface NewsDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewsDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string date = 2;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.ListOfComment listComment = 5;</code>
   * @return Whether the listComment field is set.
   */
  boolean hasListComment();
  /**
   * <code>.ListOfComment listComment = 5;</code>
   * @return The listComment.
   */
  com.plethora.TestworkClevertec2021.dto.ListOfComment getListComment();
  /**
   * <code>.ListOfComment listComment = 5;</code>
   */
  com.plethora.TestworkClevertec2021.dto.ListOfCommentOrBuilder getListCommentOrBuilder();
}
